import 'react';
import 'react-dom';
import 'react-tap-event-plugin';
import 'classnames';
import 'lodash';
import 'html-entities';
import 'react-transform-hmr';
import 'react-transform-catch-errors';
import 'react-proxy';
