import './styles/app.less';
import * as injectTapEventPlugin from 'react-tap-event-plugin';
import animationFrame from './util/animationFrame';
injectTapEventPlugin();
animationFrame();
import {px2rem, htmlFontSize} from './util/util';
export {default as Alert} from './Alert';
export {default as Button} from './Button';
export {default as Icon} from './Icon';
export {default as Line} from './Line';
export {default as Tabs} from './Tabs';
export {default as Tab} from './Tabs/Tab';
export {default as TabBar} from './TabBar/TabBar';
export {default as TabBarItem} from './TabBar/TabBarItem';
export {default as SegmentedControl} from './SegmentedControl';
export {default as LinearProgress} from './LinearProgress';
export {default as Carousel} from './Carousel';
export {default as Badge} from './Badge';
export {default as Message} from './Message';
export {default as Card} from './Card';
export {default as Switch} from './Switch';
export {default as Checkbox} from './Checkbox';
export {default as Radio} from './Radio';
export {default as RadioGroup} from './Radio/RadioGroup';
export {default as Ellipsis} from './Ellipsis';
export {default as Table} from './Table';
export {default as Arrow} from './Arrow';