let allAPI = {
    'Alert': {name: '弹窗'},
    'Arrow': {name: '箭头'},
    'Badge': {name: '徽标'},
    'Button': {name: '按钮'},
    'Card': {name: '卡片'},
    'Carousel': {name: '轮播图'},
    'Checkbox': {name: '复选框'},
    'CircleProgress': {name: '圆形进度条'},
    'Dialog': {name: '弹窗容器'},
    'Ellipsis': {name: '省略号'},
    'Icon': {name: '图标'},
    'InputItem': {name: '输入框'},
    'Line': {name: '线条'},
    'LinearProgress': {name: '限行进度条'},
    'Popup': {name: '弹层'},
    'Radio': {name: '单选框'},
    'SegmentedControl': {name: '分段控制器'},
    'Slider': {name: '滑动条'},
    'Switch': {name: '滑动开关'},
    'TabBar': {name: '底部tab'},
    'Table': {name: '表格'},
    'Tabs': {name: '切换'},
    'Toast': {name: '提示'},
};
export default allAPI;